### PR TITLE
TrueFit MissingNumber Solution

### PR DESCRIPTION
**Pull request by cswick**
Josh,

Here is my solution for the MissingNumber coding challenge/test. I made a simple C# Console Application that takes a flat file as an input and performs the necessary functions. I wasn't sure if you wanted the entire C# project, or just the files, so I included everything.

Take care,

Corey

### CODE REVIEW

**Comment by jgretz** [comment]
code received and is being reviewed.

thanks

**Comment by jgretz** [comment]
Corey,

Thanks for the code submission. I’d like to setup a quick call for you and I to walk through your code. Is there a time this week or next you have available we could chat?

Josh Gretz |  Truefit  | T  724.772.5959 | M 412.352.4413 |  www.truefitinnovation.comhttp://www.truefitinnovation.com/

**Comment by cswick** [comment]
Josh,

Thank you for getting back to me. I'm available next Tuesday at 4:30 if
that works for you. If not, let me know.

Corey

**Comment by jgretz** [comment]
4:30 works for me.

I’ll call you then

Josh Gretz |  Truefit  | T  724.772.5959 | M 412.352.4413 |  www.truefitinnovation.comhttp://www.truefitinnovation.com/

**Pull request closed without merging**
